### ISSUE TITLE
Epic: AI subsystem

### ISSUE THREAD

**Issue by milivojm** [CntoDev/cnto-conquest#4]
This is an epic containing all enemy and friendly AI units spawning and deleting throughout the Conquest game mode. Issues linked with this epic will be created and linked below.

- [x] Populate the map on mission start #5 
- [x] Recruit friendly AI (server-side backend) #6
- [x] Recruit friendly AI (client-side UI - frontend) #7 

All configuration will be maintained in `CNTOConquest` class, subclasses `Enemy` and `Friendly`. Configuration metadata for initial prototype will be kept simple as possible.
